export const env = {
  MAX_POLL_TITLE_LENGTH: 100,
  MAX_POLL_DESCRIPTION_LENGTH: 1000,
  MAX_POLL_OPTION_LENGTH: 200,
  MIN_POLL_OPTIONS: 2,
  MAX_POLL_OPTIONS: 10,
};

export const TOKEN_SYMBOL = 'ICP'; 